/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_loften_ndksample_JniTest */

#ifndef _Included_com_loften_ndksample_JniTest
#define _Included_com_loften_ndksample_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_loften_ndksample_JniTest
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loften_ndksample_JniTest_test
  (JNIEnv *, jclass);

/*
 * Class:     com_loften_ndksample_JniTest
 * Method:    combine
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loften_ndksample_JniTest_combine
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_loften_ndksample_JniTest
 * Method:    getIntArray
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_loften_ndksample_JniTest_getIntArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_loften_ndksample_JniTest
 * Method:    sortIntArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_loften_ndksample_JniTest_sortIntArray
  (JNIEnv *, jclass, jintArray);

/*
 * Class:     com_loften_ndksample_JniTest
 * Method:    creatBean
 * Signature: (Ljava/lang/String;I)Lcom/loften/ndksample/Bean;
 */
JNIEXPORT jobject JNICALL Java_com_loften_ndksample_JniTest_creatBean
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_loften_ndksample_JniTest
 * Method:    getBeanString
 * Signature: (Lcom/loften/ndksample/Bean;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_loften_ndksample_JniTest_getBeanString
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_loften_ndksample_JniTest
 * Method:    ModifyBean
 * Signature: (Lcom/loften/ndksample/Bean;)V
 */
JNIEXPORT void JNICALL Java_com_loften_ndksample_JniTest_ModifyBean
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
